stages:
  - module-pipeline

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

helm:
  stage: module-pipeline
  trigger:
    include: chart/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - chart/**/*

terraform:
  stage: module-pipeline
  trigger:
    include: terraform/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - terraform/**/*
  except:
    variables:
      - $CI_PIPELINE_SOURCE == "pipeline"