---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIllTNWphR1Z5YTJGemFHbHVPbTVpYXpsS1BEaFYiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
