---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
      - "{{ .Values.fqdn }}"
      secretName: letsencrypt
  rules:
    # Хост определяет правило направления траффика по доменному имени
    - host: "{{ .Values.fqdn }}"
      http:
        # Для различных путей в URL можно указать различные бэкенд-сервисы
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
              # Заранее создан сервис типа ClusterIP
              # Он выступает в качестве бэкенда нашего Ingress
                name: {{ .Chart.Name }}
                port:
                # У сервиса может быть несколько портов, указываем нужный нам
                  number: {{ .Values.service.port }}
