project: momo-store
source:
  repoURL: 'https://nexus.praktikum-services.ru/repository/06-a-cherkashin-momo-store/'
  targetRevision: x
  chart: momo-store
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
