apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: momo-store
spec:
  destination:
    name: ''
    namespace: momo-store
    server: 'https://kubernetes.default.svc'
  source:
    path: chart
    repoURL: 'https://gitlab.praktikum-services.ru/a.cherkashin/momo-infrastructure.git'
    targetRevision: HEAD
  project: momo-store
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
