# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
  namespace: momo-store
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIllTNWphR1Z5YTJGemFHbHVPbTVpYXpsS1BEaFYiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
